### ISSUE TITLE
文件上传时，flutter回调获取不到结果

### ISSUE THREAD

**Issue by Zhanghaitao1101** [OpenFlutter/tencent_cos#4]
Future<Null> _handleMessages(MethodCall call) async {
    print(call.arguments);
    if(call.method == "onProgress"){
      print('文件上传 onProgress');//走
    }else if(call.method == "onFailed"){
      print('文件上传 onFailed');//文件上传失败不走这里
    }else if(call.method == "onSuccess"){
      print('文件上传 onSuccess');//文件上传成功不走这里
    }

**Comment by Zhanghaitao1101** [comment]
解决方案：修改插件里的文件TencentCosPlugin，在onSuccess回调中调用channel.invokeMethod("onSuccess", data);在onFail回调中调用channel.invokeMethod("onFailed", data);

**Comment by 761713694** [comment]
修改完下次编译,又会被覆盖,有没有彻底的解决方案

**Comment by 761713694** [comment]
已经修复,很完美使用,感谢作者🙏-----作者产品虽然不完美,但已经给了我很大帮助,我的问题也彻底解决了

**Comment by zhangruiyu** [comment]
😂可以提个pr&nbsp; ！


 
---原始邮件---
发件人: "美好"<notifications@github.com&gt;
发送时间: 2020年1月17日 19:58:15
收件人: "OpenFlutter/tencent_cos"<tencent_cos@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [OpenFlutter/tencent_cos] 文件上传时，flutter回调获取不到结果 (#4)



已经修复,很完美使用,感谢作者🙏-----作者产品虽然不完美,但已经给了我很大帮助,我的问题也彻底解决了

**Comment by zhangruiyu** [comment]
可以试试我做的flutterjsonbeanfactory
，目前最好用的json转实体类插件
 
---原始邮件---
发件人: "美好"<notifications@github.com&gt;
发送时间: 2020年1月17日 19:58:15
收件人: "OpenFlutter/tencent_cos"<tencent_cos@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [OpenFlutter/tencent_cos] 文件上传时，flutter回调获取不到结果 (#4)



已经修复,很完美使用,感谢作者🙏-----作者产品虽然不完美,但已经给了我很大帮助,我的问题也彻底解决了

**Comment by 761713694** [comment]
有没有正在做xmpp的,相互沟通下

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/tencent_cos
