### ISSUE TITLE
使用fake_push插件的demo时，只要加入tencent_cos: ^0.1.4这个插件就会导致运行不起来，我做过测试两个插件可以独立运行使用，

### ISSUE THREAD

**Issue by Zhanghaitao1101** [OpenFlutter/tencent_cos#5]
fake_push插件demo地址：https://github.com/v7lin/fake_push，在此demo中引入tencent_cos: ^0.1.4插件就会运行奔溃，应该是两个腾讯的插件不兼容的问题， 但我未找到很好的解决方案

**Comment by zhangruiyu** [comment]
整极光啊 那么好用

**Comment by Zhanghaitao1101** [comment]
我解决不了这个问题，替代方案就是用极光的了，另外很感谢你提供的这个对象存储插件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "瑞宇"<notifications@github.com&gt;; 
发送时间: 2019年11月26日(星期二) 下午3:52
收件人: "OpenFlutter/tencent_cos"<tencent_cos@noreply.github.com&gt;; 
抄送: "张海涛"<1148082066@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [OpenFlutter/tencent_cos] 使用fake_push插件的demo时，只要加入tencent_cos: ^0.1.4这个插件就会导致运行不起来，我做过测试两个插件可以独立运行使用， (#5)




整极光啊 那么好用

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/tencent_cos
