### ISSUE TITLE
您好， 我引入到项目中， 报了这个错 启动不了是怎么回事呢 ？The plugin `tencent_cos` doesn't have a main class defined in D:\flutter1.17.1\flutter\.pub-cache\hosted\pub.flutter-io.cn\tencent_cos-0.1.4\android\src\main\java\com\ruiyu\tencentcos\tencentcos\TencentCosPlugin.java or D:\flutter1.17.1\flutter\.pub-cache\hosted\pub.flutter-io.cn\tencent_cos-0.1.4\android\src\main\kotlin\com\ruiyu\tencentcos\tencentcos\TencentCosPlugin.kt. This is likely to due to an incorrect `androidPackage: com.ruiyu.tencentcos.tencentcos` or `mainClass` entry in the plugin's pubspec.yaml. If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 

### ISSUE THREAD

**Issue by xiaozhangwx** [OpenFlutter/tencent_cos#7]
您好， 我引入到项目中， 报了这个错 启动不了是怎么回事呢 ？

The plugin `tencent_cos` doesn't have a main class defined in D:\flutter1.17.1\flutter\.pub-cache\hosted\pub.flutter-io.cn\tencent_cos-0.1.4\android\src\main\java\com\ruiyu\tencentcos\tencentcos\TencentCosPlugin.java or D:\flutter1.17.1\flutter\.pub-cache\hosted\pub.flutter-io.cn\tencent_cos-0.1.4\android\src\main\kotlin\com\ruiyu\tencentcos\tencentcos\TencentCosPlugin.kt. This is likely to due to an incorrect `androidPackage: com.ruiyu.tencentcos.tencentcos` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

**Comment by ChuanWSwist** [comment]
Same question

**Comment by 17it** [comment]
> 您好， 我引入到项目中， 报了这个错 启动不了是怎么回事呢 ？
> 
> The plugin `tencent_cos` doesn't have a main class defined in D:\flutter1.17.1\flutter.pub-cache\hosted\pub.flutter-io.cn\tencent_cos-0.1.4\android\src\main\java\com\ruiyu\tencentcos\tencentcos\TencentCosPlugin.java or D:\flutter1.17.1\flutter.pub-cache\hosted\pub.flutter-io.cn\tencent_cos-0.1.4\android\src\main\kotlin\com\ruiyu\tencentcos\tencentcos\TencentCosPlugin.kt. This is likely to due to an incorrect `androidPackage: com.ruiyu.tencentcos.tencentcos` or `mainClass` entry in the plugin's pubspec.yaml.
> If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

使用指定的0.1.2版本，别用最新的，如：

tencent_cos: 0.1.2

**Comment by 17it** [comment]
tencent_cos: 0.1.2

**Comment by zhangruiyu** [comment]
https://github.com/zhangruiyu/tencent_cos
